[build]
# Set the base image
image = "node:18-alpine"

[install]
# Install dependencies with legacy peer deps
command = "npm install --legacy-peer-deps"

[build.packages]
# List any packages you need to install
dependencies = [
  "node_modules/.bin", 
  "npm@latest"
]

[run]
# Expose the port
port = 3000

# Command to run the app
command = "npm start"
