# nixpacks.toml

# Specify the version of Node.js you want to use
[phases]
install = "npm install --legacy-peer-deps"

# Optional: Specify custom build and start commands
build = "npm run build"
start = "npm run start"
